version: 2
updates:
  - package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: "weekly"
    ignore:
        - dependency-name: "iced"
  - package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
