verbose = "info"
no_progress = true

fallback_extensions = ["md"]
exclude_path = ["docs/node_modules/**", "docs/.vitepress/**"]

include_fragments = true

exclude_all_private = true
exclude = [ '^http://.*', '^https://.*', '^irc://.*', '^ircs://.*' ]
