name: Build

on:
  pull_request:
    paths:
      - "**.rs"
      - "**/Cargo.toml"
      - "Cargo.lock"
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "**/Cargo.toml"
      - "Cargo.lock"
  merge_group:
    paths:
      - "**.rs"
      - "**/Cargo.toml"
      - "Cargo.lock"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-check-clippy-test:
    name: Build, Check, Clippy, Test, & Format
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C linker=clang -C link-arg=-fuse-ld=mold"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install $(cat .github/linux-deps.txt) git mold clang
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-debug-

      - name: Check
        run: cargo check --locked --profile ci

      - name: Clippy
        run: cargo clippy --locked --profile ci --workspace --all-targets -- -D warnings

      - uses: taiki-e/install-action@d858f8113943481093e02986a7586a4819a3bfd6 # v2
        with:
          tool: cargo-nextest
      - name: Test
        run: cargo nextest run --locked --profile ci --workspace --all-targets

      - uses: dtolnay/rust-toolchain@0f1b44df7e9cbb178d781a242338dfa5e243ad7f # nightly
        with:
          components: rustfmt
      - name: Format
        run: cargo +nightly fmt --all -- --check --color=always
