name: Build

on:
  pull_request:
    paths:
      - "**.rs"
      - "**/Cargo.toml"
      - "Cargo.lock"
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "**/Cargo.toml"
      - "Cargo.lock"
  merge_group:
    paths:
      - "**.rs"
      - "**/Cargo.toml"
      - "Cargo.lock"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-check-clippy-test:
    name: Build, Check, Clippy, Test, & Format
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C linker=clang -C link-arg=-fuse-ld=mold"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install $(cat .github/linux-deps.txt) git mold clang
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-debug-

      - uses: dtolnay/rust-toolchain@master # recommended when specifying toolchain
        with:
          toolchain: stable minus 3 releases
          components: clippy
      - name: Check
        run: cargo check --locked --profile ci; cargo version
      - name: Clippy
        run: cargo clippy --locked --profile ci --workspace --all-targets -- -D warnings; cargo version

      - uses: taiki-e/install-action@15413b256f995d819248ea62704771a959284285 # v2
        with:
          tool: cargo-nextest
      - name: Test
        run: cargo nextest run --locked --profile ci --workspace --all-targets; cargo version

      - uses: dtolnay/rust-toolchain@master # recommended when specifying toolchain
        with:
          toolchain: nightly
          components: rustfmt
      - name: Format
        run: cargo +nightly fmt --all -- --check --color=always; cargo version
